# Generated by Django 4.2.6 on 2023-10-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(max_length=30, primary_key=True, serialize=False)),
                ('username', models.CharField(default='username', max_length=250)),
                ('email', models.CharField(default='example@gmail.com', max_length=250)),
                ('password', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
