# Generated by Django 4.2.6 on 2023-10-24 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_users_is_active_users_is_staff_users_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_superuser',
        ),
    ]
