# Generated by Django 4.2.6 on 2023-10-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_users_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='is_superuser',
            new_name='is_admin',
        ),
        migrations.AddField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
