# Generated by Django 4.2.6 on 2023-10-25 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_is_superuser_users_is_admin_users_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_staff',
        ),
    ]
