# Generated by Django 4.2.6 on 2023-10-18 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessons',
            old_name='course_id',
            new_name='course',
        ),
    ]
