# Generated by Django 4.2.6 on 2023-10-28 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_enroll_enrolled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enroll',
            old_name='course',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='enroll',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='lessons',
            old_name='course',
            new_name='course_id',
        ),
    ]
