# Generated by Django 4.2.6 on 2023-10-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_course_enroll_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='enrolled',
            field=models.BooleanField(default=True),
        ),
    ]
