# Generated by Django 4.2.6 on 2023-10-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lessons_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
