# Generated by Django 4.2.6 on 2023-10-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_enroll_enrolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='completed',
            field=models.BooleanField(default=True),
        ),
    ]
