# Generated by Django 4.2.6 on 2023-10-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_courses_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='files',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
